### PR TITLE
Add rust-openssl regress to libssl tests

### PR DESCRIPTION
**Pull request by botovq**
This test needs the rust and rust-openssl-tests packages to run.

### CODE REVIEW

**Comment by botovq** [comment]
I assume that I should also update various `pkg-ot*.list`. Where can I find the list of architectures they map to?

**Comment by moritzbuhl** [comment]
The latest table has an architecture row:
http://bluhm.genua.de/regress/results/latest.html
Otherwise in this table:
http://obsd-lab.genua.de/

**Comment by moritzbuhl** [comment]
riscv64: http://bluhm.genua.de/regress/results/regress-ot5.html
sparc64: http://bluhm.genua.de/regress/results/regress-ot21.html

But sparc64 hasn't been running since April.

**Comment by botovq** [comment]
In your second link, ot5 is listed as "driver development" and ot21 as "-" that's why I didn't change those lists. Should I still do so?

**Comment by moritzbuhl** [comment]
The riscv64 is regularly running regression tests, it should also install the necessary dependencies.
I will update the lists on the obsd-lab website. I will see what I can do to get sparc64 running again.

**Comment by botovq** [comment]
Thanks!

**Pull request merged**
