### PR TITLE
add ipv6 data points to plots

### PR DESCRIPTION
**Pull request by moritzbuhl**
maybe it would be nice to map to {udp,tcp}{4,6} and then create a {udp,tcp} set from that but for now ...
Also the names are too long, the tabs don't align right now.

### CODE REVIEW

**Comment by moritzbuhl** [comment]
what was the meaning of the testorder numbers again?
sorry about the syntax error

**Comment by bluhm** [comment]
Test are ordered by number.  For each test attribute I added a digit.  So tests are grouped by attribute.  First digit is IP of test machine, secons is tcpbench, iperf, udpbench, then direction, final is some internal difference.  For IPv6 I would recommend a new digit.  Linux test may use test machine digit.

**Comment by moritzbuhl** [comment]
So do I understand correctly that we have something like:
ABCD
A in enum of { 10.3.0.33, 10.3.2.35, make, fs_mark }
B in enum of { iperf3, tcpbench iperf3_-u_-b0, iperf3_-u_-b10G, udpbench } otw. 0
C in enum of { forwards, backwards } otw. 0
and D differentiates between additional params (and usually just counts upwards except for make and fs)

And enums start at 1.

**Comment by bluhm** [comment]
> And for IPv6 you would like me to append the addresses to the set of A?

How do we want do sort IPv6?  Each test adjacent to the corresponding IPv4 test?  Or all IPv6 test in a block?  Maybe a IPv6 block would be better as I want to compare IPv4 values.  An IPv6 block would work well with A.

**Comment by bluhm** [comment]
You have added the Linux IPv6 tests, but not the Linux IPv4 tests.  Be consistent.

**Comment by moritzbuhl** [comment]
resolved

**Pull request closed without merging**
